name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # WIF を使うために必須

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/460681881130/locations/global/workloadIdentityPools/github-actions-pool-2/providers/github-provider-2"
          service_account: "github-actions-deploy@omorifudosan.iam.gserviceaccount.com"
          create_credentials_file: true
          project_id: omorifudosan

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ steps.auth.outputs.credentials_file_path }}
        run: npx firebase-tools@latest deploy --only hosting --project omorifudosan --non-interactive
